project:
  type: website
  output-dir: docs

website:
  title: "Daniele Cannatella"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - education.qmd
      - about.qmd

format:
  html:
    theme:
      - zephyr
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

