project:
  type: website
  output-dir: docs

website:
  title: "Daniele Cannatella"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - teaching.qmd
    right:
      - contact.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    includes:
      in_header: bootstrap.cdn.html
    toc: false

editor: visual


