---
title: "Daniele Cannatella"
subtitle: "Urbanist | GIS Expert | Assistant Professor in Urban Data for Design"
---

I’m an urban planner with a background in landscape architecture and a strong interest in digital mapping, spatial analysis, and urban analytics.

I bring these perspectives together to study cities as complex adaptive systems, with a focus on developing data-driven, nature-based strategies to help urban environments adapt to climate change and support equitable, sustainable development.

I am currently an Assistant Professor of Urban Data Science at TU Delft, where I teach in the Architecture Bachelor and the Master programmes in Urbanism, Landscape Architecture, and Geomatics. I coordinate the course Applied Spatial Analytics for Sustainable Urban Development and lead the graduation cluster Data-Informed Design for Sustainable Urban Futures.

My work combines research, teaching, and design thinking to explore how spatial data and digital tools can inform better decision-making in urban and territorial planning.
